global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kubenodes"
    static_configs:
      - targets:
          - "192.168.100.196:9100"
          - "192.168.100.197:9100"
          - "192.168.100.198:9100"