# main.yml
# Ansible Playbook for configuring and updating kubernetes nodes

- name: Configure and Update Web Server
  hosts: kubenodes
  become: yes
  tasks:
    - name: run apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install vim
      apt: 
        name: vim
        state: present
        
